# ----------------------- #
#      Main Configs       #
# ----------------------- #

cache: off
theme: mono

markdown: markdown-extra

url: /

title: Pochika
subtitle: a lightweight blog engine

description:

author: author
author_fullname: Author Name

paginate: 6
archives_paginate: 25

#emoji_plugin:
#  enabled: false
#fenced_code_block_plugin:
#  enabled: false

profiler: off
